name: shell-demo-application
description: "app to demo deployment"
namespace: shell-demo
components:
- name: hello-world
  type: manifest
  manifests:
  - name: hello-world
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: shell-demo
spec:
  containers:
  - name: hello-world-pod
    image: testcontainers/helloworld
    resources:
      requests: 
        memory: 1Gi
