// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * ICOS Shell
 *
 * This is the ICOS Shell based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 */

package shellbackend

import (
	"encoding/json"
	"net/http"
	"strings"
)

// TrainAPIController binds http requests to an api service and writes the service results to the http response
type TrainAPIController struct {
	service TrainAPIServicer
	errorHandler ErrorHandler
}

// TrainAPIOption for how the controller is set up.
type TrainAPIOption func(*TrainAPIController)

// WithTrainAPIErrorHandler inject ErrorHandler into controller
func WithTrainAPIErrorHandler(h ErrorHandler) TrainAPIOption {
	return func(c *TrainAPIController) {
		c.errorHandler = h
	}
}

// NewTrainAPIController creates a default api controller
func NewTrainAPIController(s TrainAPIServicer, opts ...TrainAPIOption) *TrainAPIController {
	controller := &TrainAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TrainAPIController
func (c *TrainAPIController) Routes() Routes {
	return Routes{
		"TrainMetrics": Route{
			strings.ToUpper("Post"),
			"/api/v3/metrics/train",
			c.TrainMetrics,
		},
	}
}

// TrainMetrics - Trains a model on a set of metrics
func (c *TrainAPIController) TrainMetrics(w http.ResponseWriter, r *http.Request) {
	bodyParam := map[string]interface{}{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	apiKeyParam := r.Header.Get("api_key")
	result, err := c.service.TrainMetrics(r.Context(), bodyParam, apiKeyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
