lighthouse: 
  controller_timeout: 60
  
keycloak: 
  server: https://iam.core.icos-staging.10-160-3-151.sslip.io:443/
  client_id: lighthouse
  client_secret: 1LXAzO9lllWFDJS36lzTczRJPX78V6Lj
  realm: staging-continuum

components: 
  job_manager: 
    server: http://10.160.3.20:30200
    path_jobgroups: /jobmanager/groups
    path_jobs: /jobmanager/jobs
  aggregator: 
    server: http://10.160.3.20:30400
    path: /
  intelligence:
    server: http://10.160.3.20:30734
    train_metrics: /train_model_metric
    predict_metrics: /create_model_metric
    get_metrics: /show_models
    unregister_metrics: /unregister_metric
    stop_metrics: /stop_model_metrics
    delete_metrics: /remove_model
