version: '3.5'

services:
    icos-shell-backend:
        image: michalkeit/icos-shell-backend
        build: ./
        container_name: icos-shell-backend
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./config_server.yml:/app/config.yml
            - /etc/ssl/certs/icos-lh-cert.pem:/etc/ssl/certs/icos-lh-cert.pem
