FROM node:18-alpine
WORKDIR /app

# Install specific dependencies
RUN npm install express@^4.17.1
RUN npm install http-proxy-middleware@^1.0.6
RUN npm install cors@^2.8.5

COPY request_handler.js .

CMD ["node", "request_handler.js"]
