/*
ICOS Shell

Testing DefaultApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	"shellclient/cmd"
	openapi "shellclient/pkg/openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_DefaultApiService(t *testing.T) {

	cmd.InitConfigForTesting()
	apiClient := openapi.Client

	t.Run("Test DefaultApiService GetHealthcheck", func(t *testing.T) {

		// t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetHealthcheck(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
